webapp/Logistics/urls.py
from django.urls import path
from .views import invoice

app_name = 'Logistics'

urlpatterns = [
    path("home/", invoice.HomeView.as_view(), name="home"),
    path("invoice_display/", invoice.InvoiceDisplayView.as_view(), name="invoice_display"),
    path("invoiceitem_display/", invoice.InvoiceItemDisplayView.as_view(), name="invoiceitem_display"),
    path("invoice_form/", invoice.InvoiceFormView.as_view(), name="invoice_form"),
    path("invoiceitem_form/", invoice.InvoiceItemFormView.as_view(), name="invoiceitem_form"),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logistics/', include('Logistics.urls', namespace='logistics')),
]

webapp/Logistics/models/invoice.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from decimal import Decimal


class Invoice(models.Model):

    date = models.DateField(unique=True)


class InvoiceItem(models.Model):

    units = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=5, default=0.0)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)

webapp/Logistics/forms/invoice.py
from django import forms

from bootstrap_datepicker_plus.widgets import DatePickerInput

from ..models.invoice import Invoice, InvoiceItem


#=======================================================================================================================
class InvoiceForm(forms.ModelForm):

    class Meta:

        model = Invoice
        fields = ['date']
        widgets = {
            'date': DatePickerInput(),
        }

    def __init__(self, *args, **kwargs):

        super(InvoiceForm, self).__init__(*args, **kwargs)
        self.fields['date'].required = True


#=======================================================================================================================
class JerryModelChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):

        return obj.date


#=======================================================================================================================
class InvoiceItemForm(forms.ModelForm):

    invoice = JerryModelChoiceField(
        Invoice.objects.all(),
    )

    # invoice = forms.ModelChoiceField(
    #     queryset=Invoice.objects.values_list('date', flat=True).order_by('-date'),
    #     to_field_name='date',
    #     initial=Invoice.objects.all().order_by('-date')[0],
    #     empty_label=None,
    # )

    class Meta:

        model = InvoiceItem
        fields = '__all__'
        # exclude = ('invoice',)

webapp/Logistics/views/invoice.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from bootstrap_datepicker_plus.widgets import DatePickerInput
from django.views import generic
from django.views import View

from ..models.invoice import Invoice, InvoiceItem
from ..forms.invoice import InvoiceForm, InvoiceItemForm

from datetime import datetime


#=======================================================================================================================
class HomeView(View):

    def get(self, request):
        template = 'Logistics/home.html'
        return render(request, template)


#=======================================================================================================================
class InvoiceDisplayView(View):

    def get(self, request):
        data_list = Invoice.objects.all().order_by('id')
        template = 'Logistics/invoice_display.html'
        return render(request, template, context={'data_list': data_list})


#=======================================================================================================================
class InvoiceItemDisplayView(View):

    def get(self, request):
        data_list = InvoiceItem.objects.select_related('invoice').values(
            'units', 'description', 'amount', 'invoice__date').order_by('id')
        template = 'Logistics/invoice_item_display.html'
        return render(request, template, context={'data_list': data_list})


#=======================================================================================================================
class InvoiceFormView(generic.edit.CreateView):

    model = Invoice
    fields = ['date']

    def get(self, request):
        form = InvoiceForm()
        form.fields['date'].widget = DatePickerInput()
        template = 'Logistics/invoice.html'
        return render(request, template, context={'form': form})

    def post(self, request):
        form = InvoiceForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            form.save()
            return redirect("Logistics:invoice_form")
        else:
            template = 'Logistics/error.html'
            msg = 'The date already exists. Please pick another date.'
            return render(request, template, context={'error_msg': msg})


#=======================================================================================================================
class InvoiceItemFormView(generic.edit.CreateView):

    model = InvoiceItem
    fields = ['units', 'description', 'amount', 'invoice']

    def get(self, request):
        form = InvoiceItemForm()
        template = 'Logistics/invoice_item.html'
        return render(request, template, context={'form': form})

    def post(self, request):
        form = InvoiceItemForm(request.POST)
        if form.is_valid():
            # data = form.cleaned_data
            form.save()
            return redirect("Logistics:invoiceitem_form")
        else:
            template = 'Logistics/error.html'
            msg = 'Invalid data.'
            return render(request, template, context={'error_msg': msg})


#=======================================================================================================================
def _flt(v, dflt=0.0):
    try:
        return float(v)
    except:
        return dflt


def _int(v, dflt=0):
    try:
        return int(v)
    except:
        return dflt

webapp/Logistics/templates/Logistics/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error Page</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <div>
        {% if error_msg %}
            <h1>{{ error_msg }}</h1>
        {% else %}
            <h1>No error available.</h1>
        {% endif %}
    </div>
    <div>
        <button onclick="location.href='{% url 'Logistics:invoice_form' %}'">Go to Invoice Form</button>
    </div>
    <br>
    <div>
        <button onclick="location.href='{% url 'Logistics:invoiceitem_form' %}'">Go to Invoice Item Form</button>
    </div>
    <br>
    <div>
        <button onclick="location.href='{% url 'Logistics:home' %}'">Home Page</button>
    </div>
</body>
</html>

webapp/Logistics/templates/Logistics/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logistics Home Page</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <h1>Welcome to EastRidge Logistics Home Page</h1>
    <button onclick="location.href='{% url 'Logistics:invoice_form' %}'">Click to view Invoice Form</button>
    <button onclick="location.href='{% url 'Logistics:invoiceitem_form' %}'">Click to view Invoice Item Form</button>
</body>
</html>

webapp/Logistics/templates/Logistics/invoice.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div>
    <form action="{% url 'Logistics:invoice_form' %}" method="post">
        {% csrf_token %}
        {% if form %}
            <h1>This is an Invoice Form</h1>
            <div style="width:200">
                {% bootstrap_form form %}
            </div>
        {% else %}
            <p>No forms are available.</p>
        {% endif %}
        <input type="submit" value="Submit" />
    </form>
</div>
<div>
    <button onclick="location.href='{% url 'Logistics:invoice_display' %}'">Display all Invoice data</button>
</div>
<br>
<div>
    <button onclick="location.href='{% url 'Logistics:home' %}'">Home Page</button>
</div>

webapp/Logistics/templates/Logistics/invoice_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <h1>All available invoice:</h1>
    <div>
        {% if data_list %}
        <ul>
            {% for data in data_list %}
                <li></b>{{ forloop.counter }}. Date: {{ data.date }} (ID: {{ data.id }})</b></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No data available.</p>
        {% endif %}
    </div>
    <div>
        <button onclick="location.href='{% url 'Logistics:invoice_form' %}'">Go back</button>
    </div>
    <br>
    <div>
        <button onclick="location.href='{% url 'Logistics:home' %}'">Home Page</button>
    </div>
</body>
</html>

webapp/Logistics/templates/Logistics/invoice_item.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div>
    <form action="{% url 'Logistics:invoiceitem_form' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form %}
            <h1>This is an Invoice Item Form</h1>
            <h5>(units, description can be blank)</h5>
            <div style="width:250">
                {% bootstrap_form form %}
<!--                {{ form.as_p }}-->
            </div>
        {% else %}
            <p>No forms are available.</p>
        {% endif %}
        <input type="submit" value="Submit" />
    </form>
</div>
<div>
    <button onclick="location.href='{% url 'Logistics:invoiceitem_display' %}'">Display all Invoice Item data</button>
</div>
<br>
<div>
    <button onclick="location.href='{% url 'Logistics:home' %}'">Home Page</button>
</div>

webapp/Logistics/templates/Logistics/invoice_item_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <h1>All available invoice items:</h1>
    <div>
        {% if data_list %}
        <ul>
            {% for data in data_list %}
                <li>{{ forloop.counter }}. Units: {{ data.units }}, Description: {{ data.description }}, Amount: {{ data.amount }} (Date: {{ data.invoice__date }})</li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No data available.</p>
        {% endif %}
    </div>
    <div>
        <button onclick="location.href='{% url 'Logistics:invoiceitem_form' %}'">Go back</button>
    </div>
    <br>
    <div>
        <button onclick="location.href='{% url 'Logistics:home' %}'">Home Page</button>
    </div>
</body>
</html>